create table books
(
    id_book          serial
        primary key,
    title            varchar not null,
    author           varchar not null,
    publication_year varchar not null,
    synopsis         text    not null,
    book_cover       varchar not null,
    state            boolean not null,
    stock_total      integer not null,
    stock_remaining  integer not null,
    genre            varchar not null
);

alter table books
    owner to postgres;

INSERT INTO public.books (id_book, title, author, publication_year, synopsis, book_cover, state, stock_total, stock_remaining, genre) VALUES (21, 'Klara and the Sun', 'Kazuo Ishiguro', '2021', e'From her place in the store, Klara, an Artificial Friend with outstanding observational qualities, watches carefully the behavior of those who come in to browse, and of those who pass on the street outside. She remains hopeful that a customer will soon choose her, but when the possibility emerges that her circumstances may change forever, Klara is warned not to invest too much in the promises of humans.

In Klara and the Sun, Kazuo Ishiguro looks at our rapidly changing modern world through the eyes of an unforgettable narrator to explore a fundamental question: what does it mean to love?', 'klaraAndTheSun.jpg', true, 5, 4, 'science fiction');
INSERT INTO public.books (id_book, title, author, publication_year, synopsis, book_cover, state, stock_total, stock_remaining, genre) VALUES (23, 'Romeo and Juliet', 'William Shakespeare', '1597', e'In Romeo and Juliet, Shakespeare creates a violent world, in which two young people fall in love. It is not simply that their families disapprove; the Montagues and the Capulets are engaged in a blood feud.

In this death-filled setting, the movement from love at first sight to the lovers’ final union in death seems almost inevitable. And yet, this play set in an extraordinary world has become the quintessential story of young love. In part because of its exquisite language, it is easy to respond as if it were about all young lovers.', 'romeoAndJuliet.jpg', true, 9, 6, 'classics');
INSERT INTO public.books (id_book, title, author, publication_year, synopsis, book_cover, state, stock_total, stock_remaining, genre) VALUES (2, 'Crooked Kingdom', 'Leigh Bardugo', '2016', e'Welcome to the world of the Grisha.

Kaz Brekker and his crew of deadly outcasts have just pulled off a heist so daring even they didn\'t think they\'d survive. But instead of divvying up a fat reward, they\'re right back to fighting for their lives.

Double-crossed and badly weakened, the crew is low on resources, allies, and hope. As powerful forces from around the world descend on Ketterdam to root out the secrets of the dangerous drug known as jurda parem, old rivals and new enemies emerge to challenge Kaz\'s cunning and test the team\'s fragile loyalties.

A war will be waged on the city\'s dark and twisting streets - a battle for revenge and redemption that will decide the fate of the Grisha world.', 'crookedKingdom.jpg', true, 5, 3, 'fantasy');
INSERT INTO public.books (id_book, title, author, publication_year, synopsis, book_cover, state, stock_total, stock_remaining, genre) VALUES (5, 'The Little Prince', 'Antoine de Saint-Exupéry', '1943', 'A pilot stranded in the desert awakes one morning to see, standing before him, the most extraordinary little fellow. Please asks the stranger, \"draw me a sheep.\" And the pilot realizes that when life''s events are too difficult to understand, there is no choice but to succumb to their mysteries. He pulls out pencil and paper... And thus begins this wise and enchanting fable that, in teaching the secret of what is really important in life, has changed forever the world for its readers', 'theLittlePrince.jpg', true, 12, 7, 'classics');
INSERT INTO public.books (id_book, title, author, publication_year, synopsis, book_cover, state, stock_total, stock_remaining, genre) VALUES (1, 'Six Of Crows', 'Leigh Bardugo', '2015', 'Ketterdam: a bustling hub of international trade where anything can be had for the right price—and no one knows that better than criminal prodigy Kaz Brekker. Kaz is offered a chance at a deadly heist that could make him rich beyond his wildest dreams. But he can’t pull it off alone...\n A convict with a thirst for revenge \nA sharpshooter who can’t walk away from a wager\nA runaway with a privileged past \nA spy known as the Wraith \nA Heartrender using her magic to survive the slums    \nA thief with a gift for unlikely escapes\nSix dangerous outcasts. One impossible heist. Kaz’s crew is the only thing that might stand between the world and destruction—if they don’t kill each other first.', 'sixOfCrows.jpg', true, 8, 4, 'fantasy');
INSERT INTO public.books (id_book, title, author, publication_year, synopsis, book_cover, state, stock_total, stock_remaining, genre) VALUES (6, 'Cinder', 'Marissa Meyer', '2012', 'Humans and androids crowd the raucous streets of New Beijing. A deadly plague ravages the population. From space, a ruthless Lunar people watch, waiting to make their move. No one knows that Earth’s fate hinges on one girl. . . . Cinder, a gifted mechanic, is a cyborg.\nShe’s a second-class citizen with a mysterious past, reviled by her stepmother and blamed for her stepsister’s illness. But when her life becomes intertwined with the handsome Prince Kai’s, she suddenly finds herself at the center of an intergalactic struggle, and a forbidden attraction. Caught between duty and freedom, loyalty and betrayal, she must uncover secrets about her past in order to protect her world’s future.', 'cinder.jpg', true, 5, 2, 'fantasy');
INSERT INTO public.books (id_book, title, author, publication_year, synopsis, book_cover, state, stock_total, stock_remaining, genre) VALUES (7, 'Scarlet', 'Marissa Meyer', '2013', e'She’s trying to break out of prison—even though if she succeeds, she’ll be the Commonwealth’s most wanted fugitive. Halfway around the world, Scarlet Benoit’s grandmother is missing. It turns out there are many things Scarlet doesn’t know about her grandmother and the grave danger she has lived in her whole life.

When Scarlet encounters Wolf, a street fighter who may have information as to her grandmother’s whereabouts, she has no choice but to trust him, though he clearly has a few dark secrets of his own. As Scarlet and Wolf work to unravel one mystery, they find another when they cross paths with Cinder. Together, they must stay one step ahead of the vicious Lunar Queen who will do anything to make Prince Kai her husband, her king, her prisoner.', 'scarlet.jpg', true, 4, 1, 'fantasy');
INSERT INTO public.books (id_book, title, author, publication_year, synopsis, book_cover, state, stock_total, stock_remaining, genre) VALUES (8, 'Cress', 'Marissa Meyer', '2014', e'In this third book in the Lunar Chronicles, Cinder and Captain Thorne are fugitives on the run, now with Scarlet and Wolf in tow. Together, they\'re plotting to overthrow Queen Levana and her army.

Their best hope lies with Cress, a girl imprisoned on a satellite since childhood who\'s only ever had her netscreens as company. All that screen time has made Cress an excellent hacker. Unfortunately, she\'s just received orders from Levana to track down Cinder and her handsome accomplice.

When a daring rescue of Cress goes awry, the group is separated. Cress finally has her freedom, but it comes at a higher price. Meanwhile, Queen Levana will let nothing prevent her marriage to Emperor Kai. Cress, Scarlet, and Cinder may not have signed up to save the world, but they may be the only hope the world has.
When Scarlet encounters Wolf, a street fighter who may have information as to her grandmother’s whereabouts, she has no choice but to trust him, though he clearly has a few dark secrets of his own. As Scarlet and Wolf work to unravel one mystery, they find another when they cross paths with Cinder. Together, they must stay one step ahead of the vicious Lunar Queen who will do anything to make Prince Kai her husband, her king, her prisoner.', 'cress.jpg', true, 4, 2, 'fantasy');
INSERT INTO public.books (id_book, title, author, publication_year, synopsis, book_cover, state, stock_total, stock_remaining, genre) VALUES (12, 'The Queen of Nothing', 'Holly Black', '2019', e'He will be destruction of the crown and the ruination of the throne.

Power is much easier to acquire than it is to hold onto. Jude learned this lesson when she released her control over the wicked king, Cardan, in exchange for immeasurable power.

Now as the exiled mortal Queen of Faerie, Jude is powerless and left reeling from Cardan’s betrayal. She bides her time determined to reclaim everything he took from her. Opportunity arrives in the form of her deceptive twin sister, Taryn, whose mortal life is in peril.

Jude must risk venturing back into the treacherous Faerie Court, and confront her lingering feelings for Cardan, if she wishes to save her sister. But Elfhame is not as she left it. War is brewing. As Jude slips deep within enemy lines she becomes ensnared in the conflict’s bloody politics.

And, when a dormant yet powerful curse is unleashed, panic spreads throughout the land, forcing her to choose between her ambition and her humanity…', 'theQueenOfNothing.jpg', true, 5, 2, 'fantasy');
INSERT INTO public.books (id_book, title, author, publication_year, synopsis, book_cover, state, stock_total, stock_remaining, genre) VALUES (11, 'The Wicked King', 'Holly Black', '2019', e'You must be strong enough to strike and strike and strike again without tiring.

The first lesson is to make yourself strong.

After the jaw-dropping revelation that Oak is the heir to Faerie, Jude must keep her brother safe. To do so, she has bound the wicked king, Cardan, to her, and made herself the power behind the throne. Navigating the constantly shifting political alliances of Faerie would be difficult enough if Cardan were easy to control. But he does everything in his power to humiliate and undermine her even as his fascination with her remains undiminished.

When it becomes all too clear that someone close to Jude means to betray her, threatening her own life and the lives of everyone she loves, Jude must uncover the traitor and fight her own complicated feelings for Cardan to maintain control as a mortal in a Faerie world.', 'theWickedKing.jpg', true, 5, 2, 'fantasy');
INSERT INTO public.books (id_book, title, author, publication_year, synopsis, book_cover, state, stock_total, stock_remaining, genre) VALUES (10, 'The Cruel Prince', 'Holly Black', '2018', e'Of course I want to be like them. They’re beautiful as blades forged in some divine fire. They will live forever.

And Cardan is even more beautiful than the rest. I hate him more than all the others. I hate him so much that sometimes when I look at him, I can hardly breathe.

Jude was seven when her parents were murdered and she and her two sisters were stolen away to live in the treacherous High Court of Faerie. Ten years later, Jude wants nothing more than to belong there, despite her mortality. But many of the fey despise humans. Especially Prince Cardan, the youngest and wickedest son of the High King.

To win a place at the Court, she must defy him–and face the consequences.

As Jude becomes more deeply embroiled in palace intrigues and deceptions, she discovers her own capacity for trickery and bloodshed. But as betrayal threatens to drown the Courts of Faerie in violence, Jude will need to risk her life in a dangerous alliance to save her sisters, and Faerie itself.', 'theCruelPrince.jpg', true, 5, 2, 'fantasy');
INSERT INTO public.books (id_book, title, author, publication_year, synopsis, book_cover, state, stock_total, stock_remaining, genre) VALUES (13, 'Pride and Prejudice', 'Jane Austen', '1813', 'Since its immediate success in 1813, Pride and Prejudice has remained one of the most popular novels in the English language. Jane Austen called this brilliant work "her own darling child" and its vivacious heroine, Elizabeth Bennet, "as delightful a creature as ever appeared in print." The romantic clash between the opinionated Elizabeth and her proud beau, Mr. Darcy, is a splendid performance of civilized sparring. And Jane Austen''s radiant wit sparkles as her characters dance a delicate quadrille of flirtation and intrigue, making this book the most superb comedy of manners of Regency England.', 'prideAndPrejudice.jpg', true, 10, 4, 'classics');
INSERT INTO public.books (id_book, title, author, publication_year, synopsis, book_cover, state, stock_total, stock_remaining, genre) VALUES (17, 'Murder on the Orient Express', 'Agatha Christie', '1934', e'Just after midnight, a snowdrift stops the famous Orient Express in its tracks as it travels through the mountainous Balkans. The luxurious train is surprisingly full for the time of the year but, by the morning, it is one passenger fewer. An American tycoon lies dead in his compartment, stabbed a dozen times, his door locked from the inside.

One of the passengers is none other than detective Hercule Poirot. On vacation.

Isolated and with a killer on board, Poirot must identify the murderer—in case he or she decides to strike again.', 'murderOrientExpress.jpg', true, 8, 7, 'mistery');
INSERT INTO public.books (id_book, title, author, publication_year, synopsis, book_cover, state, stock_total, stock_remaining, genre) VALUES (14, 'Northanger Abbey', 'Jane Austen', '1817', e'A wonderfully entertaining coming-of-age story, Northanger Abbey is often referred to as Jane Austen\'s "Gothic parody." Decrepit castles, locked rooms, mysterious chests, cryptic notes, and tyrannical fathers give the story an uncanny air, but one with a decidedly satirical twist.

The story\'s unlikely heroine is Catherine Morland, a remarkably innocent seventeen-year-old woman from a country parsonage. While spending a few weeks in Bath with a family friend, Catherine meets and falls in love with Henry Tilney, who invites her to visit his family estate, Northanger Abbey. Once there, Catherine, a great reader of Gothic thrillers, lets the shadowy atmosphere of the old mansion fill her mind with terrible suspicions. What is the mystery surrounding the death of Henry\'s mother? Is the family concealing a terrible secret within the elegant rooms of the Abbey? Can she trust Henry, or is he part of an evil conspiracy? Catherine finds dreadful portents in the most prosaic events, until Henry persuades her to see the peril in confusing life with art.

Executed with high-spirited gusto, Northanger Abbey is a lighthearted, yet unsentimental commentary on love and marriage.', 'northangerAbby.jpg', true, 10, 6, 'classics');
INSERT INTO public.books (id_book, title, author, publication_year, synopsis, book_cover, state, stock_total, stock_remaining, genre) VALUES (15, 'Emma', 'Jane Austen', '1815', 'Emma Woodhouse is one of Austen''s most captivating and vivid characters. Beautiful, spoilt, vain and irrepressibly witty, Emma organizes the lives of the inhabitants of her sleepy little village and plays matchmaker with devastating effect.', 'emma.jpg', true, 6, 6, 'classics');
INSERT INTO public.books (id_book, title, author, publication_year, synopsis, book_cover, state, stock_total, stock_remaining, genre) VALUES (16, 'Wuthering Heights', 'Emily Brontë', '1847', 'At the centre of this novel is the passionate love between Catherine Earnshaw and Heathcliff - recounted with such emotional intensity that a plain tale of the Yorkshire moors acquires the depth and simplicity of ancient tragedy.', 'wutheringHeights.jpg', true, 6, 6, 'classics');
INSERT INTO public.books (id_book, title, author, publication_year, synopsis, book_cover, state, stock_total, stock_remaining, genre) VALUES (9, 'Winter', 'Marissa Meyer', '2015', 'Princess Winter is admired for her grace, kindness and beauty, despite the scars on her face. She''s said to be even more breath-taking than her stepmother, Queen Levana...\n\nWhen Winter develops feelings for the handsome palace guard, Jacin, she fears the evil Queen will crush their romance before it has a chance to begin.\n\nBut there are stirrings against the Queen across the land. Together with the cyborg mechanic, Cinder, and her allies, Winter might even find the power to launch a revolution and win a war that''s been raging for far too long.\n\nCan Cinder, Scarlet, Cress, and Winter claim their happily ever afters by defeating Levana once and for all?\nTheir best hope lies with Cress, a girl imprisoned on a satellite since childhood who''s only ever had her netscreens as company. All that screen time has made Cress an excellent hacker. Unfortunately, she''s just received orders from Levana to track down Cinder and her handsome accomplice.\n\nWhen a daring rescue of Cress goes awry, the group is separated. Cress finally has her freedom, but it comes at a higher price. Meanwhile, Queen Levana will let nothing prevent her marriage to Emperor Kai. Cress, Scarlet, and Cinder may not have signed up to save the world, but they may be the only hope the world has.\nWhen Scarlet encounters Wolf, a street fighter who may have information as to her grandmother’s whereabouts, she has no choice but to trust him, though he clearly has a few dark secrets of his own. As Scarlet and Wolf work to unravel one mystery, they find another when they cross paths with Cinder. Together, they must stay one step ahead of the vicious Lunar Queen who will do anything to make Prince Kai her husband, her king, her prisoner.', 'winter.jpg', false, 3, 0, 'fantasy');
INSERT INTO public.books (id_book, title, author, publication_year, synopsis, book_cover, state, stock_total, stock_remaining, genre) VALUES (18, 'If We Were Villains', 'M. L. Rio', '2017', e'Oliver Marks has just served ten years for a murder he may or may not have committed. On the day of his release, he is greeted by the detective who put him in prison. Detective Colborne is retiring, and he wants to know what really happened a decade before.

As a young actor at an elite conservatory, Oliver noticed that his talented classmates seem to play the same characters onstage and off – villain, hero, temptress – though he was always a supporting role. But when the teachers change the casting, a good-natured rivalry turns ugly, and the plays spill dangerously over into real life.

When tragedy strikes, one of the seven friends is found dead. The rest face their greatest acting challenge yet: convincing the police, and themselves, that they are blameless...', 'ifWeWereVillains.jpg', true, 2, 2, 'mistery');
INSERT INTO public.books (id_book, title, author, publication_year, synopsis, book_cover, state, stock_total, stock_remaining, genre) VALUES (19, 'The Love Hypothesis', 'Ali Hazelwood', '2021', e'As a third-year Ph.D. candidate, Olive Smith doesn\'t believe in lasting romantic relationships--but her best friend does, and that\'s what got her into this situation. Convincing Anh that Olive is dating and well on her way to a happily ever after was always going to take more than hand-wavy Jedi mind tricks: Scientists require proof. So, like any self-respecting biologist, Olive panics and kisses the first man she sees.

That man is none other than Adam Carlsen, a young hotshot professor--and well-known ass. Which is why Olive is positively floored when Stanford\'s reigning lab tyrant agrees to keep her charade a secret and be her fake boyfriend. But when a big science conference goes haywire, putting Olive\'s career on the Bunsen burner, Adam surprises her again with his unyielding support and even more unyielding... six-pack abs.

Suddenly their little experiment feels dangerously close to combustion. And Olive discovers that the only thing more complicated than a hypothesis on love is putting her own heart under the microscope.
As a young actor at an elite conservatory, Oliver noticed that his talented classmates seem to play the same characters onstage and off – villain, hero, temptress – though he was always a supporting role. But when the teachers change the casting, a good-natured rivalry turns ugly, and the plays spill dangerously over into real life.

When tragedy strikes, one of the seven friends is found dead. The rest face their greatest acting challenge yet: convincing the police, and themselves, that they are blameless...', 'theLoveHypothesis.jpg', true, 4, 4, 'romance');
INSERT INTO public.books (id_book, title, author, publication_year, synopsis, book_cover, state, stock_total, stock_remaining, genre) VALUES (20, 'Fahrenheit 451', 'Ray Bradbury', '1953', 'Guy Montag is a fireman. His job is to destroy the most illegal of commodities, the printed book, along with the houses in which they are hidden. Montag never questions the destruction and ruin his actions produce, returning each day to his bland life and wife, Mildred, who spends all day with her television “family.” But when he meets an eccentric young neighbor, Clarisse, who introduces him to a past where people didn’t live in fear and to a present where one sees the world through the ideas in books instead of the mindless chatter of television, Montag begins to question everything he has ever known.', 'fahrenheit451.jpg', true, 5, 4, 'science fiction');
INSERT INTO public.books (id_book, title, author, publication_year, synopsis, book_cover, state, stock_total, stock_remaining, genre) VALUES (22, 'Hamlet', 'William Shakespeare', '1601', e'In this quintessential Shakespearean tragedy, a young prince\'s halting pursuit of revenge for the murder of his father unfolds in a series of highly charged confrontations that have held audiences spellbound for nearly four centuries. Those fateful exchanges, and the anguished soliloquies that precede and follow them, probe depths of human feeling rarely sounded in any art.

The title role of Hamlet, perhaps the most demanding in all of Western drama, has provided generations of leading actors their greatest challenge. Yet all of the roles in this towering drama are superbly delineated, and each of the key scenes offers actors a rare opportunity to create theatrical magic.

As if further evidence of Shakespeare\'s genius were needed, Hamlet is a unique pleasure to read as well as to see and hear performed. The full text of this extraordinary drama is reprinted here from an authoritative British edition complete with illuminating footnotes.', 'hamlet.jpg', true, 8, 4, 'classics');
INSERT INTO public.books (id_book, title, author, publication_year, synopsis, book_cover, state, stock_total, stock_remaining, genre) VALUES (24, 'Book Lovers', 'Emily Henry', '2022', e'Nora Stephens’ life is books—she’s read them all—and she is not that type of heroine. Not the plucky one, not the laidback dream girl, and especially not the sweetheart. In fact, the only people Nora is a heroine for are her clients, for whom she lands enormous deals as a cutthroat literary agent, and her beloved little sister Libby.

Which is why she agrees to go to Sunshine Falls, North Carolina for the month of August when Libby begs her for a sisters’ trip away—with visions of a small-town transformation for Nora, who she’s convinced needs to become the heroine in her own story. But instead of picnics in meadows, or run-ins with a handsome country doctor or bulging-forearmed bartender, Nora keeps bumping into Charlie Lastra, a bookish brooding editor from back in the city. It would be a meet-cute if not for the fact that they’ve met many times and it’s never been cute.

If Nora knows she’s not an ideal heroine, Charlie knows he’s nobody’s hero, but as they are thrown together again and again—in a series of coincidences no editor worth their salt would allow—what they discover might just unravel the carefully crafted stories they’ve written about themselves.', 'bookLovers.jpg', true, 3, 3, 'romance');
INSERT INTO public.books (id_book, title, author, publication_year, synopsis, book_cover, state, stock_total, stock_remaining, genre) VALUES (25, 'Dune', 'Frank Herbert', '1965', e'Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the “spice” melange, a drug capable of extending life and enhancing consciousness. Coveted across the known universe, melange is a prize worth killing for...

When House Atreides is betrayed, the destruction of Paul’s family will set the boy on a journey toward a destiny greater than he could ever have imagined. And as he evolves into the mysterious man known as Muad’Dib, he will bring to fruition humankind’s most ancient and unattainable dream.', 'dune.jpg', true, 5, 3, 'science fiction');
INSERT INTO public.books (id_book, title, author, publication_year, synopsis, book_cover, state, stock_total, stock_remaining, genre) VALUES (26, 'I''m Glad My Mom Died', 'Jennette McCurdy', '2022', e'A heartbreaking and hilarious memoir by iCarly and Sam & Cat star Jennette McCurdy about her struggles as a former child actor—including eating disorders, addiction, and a complicated relationship with her overbearing mother—and how she retook control of her life.

Jennette McCurdy was six years old when she had her first acting audition. Her mother’s dream was for her only daughter to become a star, and Jennette would do anything to make her mother happy. So she went along with what Mom called “calorie restriction,” eating little and weighing herself five times a day. She endured extensive at-home makeovers while Mom chided, “Your eyelashes are invisible, okay? You think Dakota Fanning doesn’t tint hers?” She was even showered by Mom until age sixteen while sharing her diaries, email, and all her income.

In I’m Glad My Mom Died, Jennette recounts all this in unflinching detail—just as she chronicles what happens when the dream finally comes true. Cast in a new Nickelodeon series called iCarly, she is thrust into fame. Though Mom is ecstatic, emailing fan club moderators and getting on a first-name basis with the paparazzi (“Hi Gale!”), Jennette is riddled with anxiety, shame, and self-loathing, which manifest into eating disorders, addiction, and a series of unhealthy relationships. These issues only get worse when, soon after taking the lead in the iCarly spinoff Sam & Cat alongside Ariana Grande, her mother dies of cancer. Finally, after discovering therapy and quitting acting, Jennette embarks on recovery and decides for the first time in her life what she really wants.

Told with refreshing candor and dark humor, I’m Glad My Mom Died is an inspiring story of resilience, independence, and the joy of shampooing your own hair.', 'imGladMyMom.jpg', true, 5, 5, 'nonfiction');
INSERT INTO public.books (id_book, title, author, publication_year, synopsis, book_cover, state, stock_total, stock_remaining, genre) VALUES (27, 'What Moves the Dead', 'T. Kingfisher', '2022', e'What Moves the Dead is Kingfisher\'s retelling of Edgar Allan Poe\'s classic "The Fall of the House of Usher.”

When Alex Easton, a retired soldier, receives word that their childhood friend Madeline Usher is dying, they race to the ancestral home of the Ushers in the remote countryside of Ruritania.

What they find there is a nightmare of fungal growths and possessed wildlife, surrounding a dark, pulsing lake. Madeline sleepwalks and speaks in strange voices at night, and her brother Roderick is consumed with a mysterious malady of the nerves.

Aided by a redoubtable British mycologist and a baffled American doctor, Alex must unravel the secret of the House of Usher before it consumes them all.', 'whatMovesTheDead.jpg', true, 3, 3, 'horror');
